#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Lint-staged is used for linting and prettify the code before commit
# You can instead use this [npm run lint && npm run format-code]
# Enforce branch name is used for specific release flow
npx lint-staged && ./scripts/enforce-branch-name.sh
